version: '3.9'

services:
  backend:
    container_name: backend
    image: backend
    build:
      context: ./srv
      dockerfile: Dockerfile
    ports:
      - '4000:4000'

  frontend:
    container_name: frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - API_URL=http://localhost:4000
    depends_on:
      - backend
